databases:
  - name: pg-auth-db
    databaseName: user_db
    user: db_user
    plan: free

services:
  - type: web
    name: php-auth-app
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg-auth-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SESSION_SECRET
        generateValue: true
